# Cloud Run Service Definition for WhatsApp MCP Server
#
# Prerequisites:
# 1. Build and push Docker image to Artifact Registry
# 2. Create secrets in Secret Manager (via Terraform or gcloud)
# 3. Update placeholders: PROJECT_ID, REGION, SERVICE_ACCOUNT_EMAIL, REPO_NAME, TAG
#
# Deploy with:
#   gcloud run services replace cloudrun.yaml --region=REGION --project=PROJECT_ID
#
# Or use gcloud run deploy for imperative deployment:
#   gcloud run deploy whatsapp-mcp \
#     --image=REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/whatsapp-mcp:TAG \
#     --region=REGION \
#     --platform=managed \
#     --service-account=SERVICE_ACCOUNT_EMAIL \
#     --update-secrets=GOOGLE_CLIENT_ID=whatsapp-mcp-google-client-id:latest,OAUTH_AUDIENCE=whatsapp-mcp-oauth-audience:latest \
#     --set-env-vars=MCP_TRANSPORT=sse,PORT=3000,WHATSAPP_BRIDGE_URL=http://localhost:8080,GCS_SESSION_BUCKET=PROJECT_ID-whatsapp-sessions,OAUTH_ENABLED=true \
#     --port=3000 \
#     --cpu=2 \
#     --memory=2Gi \
#     --timeout=300 \
#     --max-instances=10 \
#     --min-instances=0 \
#     --no-cpu-throttling \
#     --execution-environment=gen2
#
# Note: Uses SQLite by default. For Supabase, add:
#     --update-secrets=SUPABASE_URL=whatsapp-mcp-supabase-url:latest,SUPABASE_KEY=whatsapp-mcp-supabase-key:latest
#
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: whatsapp-mcp
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Service account
        run.googleapis.com/service-account: SERVICE_ACCOUNT_EMAIL
        # Execution environment
        run.googleapis.com/execution-environment: gen2
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
        # Startup probe configuration
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: SERVICE_ACCOUNT_EMAIL
      containers:
      - name: whatsapp-mcp
        image: REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/whatsapp-mcp:TAG
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: MCP_TRANSPORT
          value: "sse"
        - name: MCP_PORT
          value: "3000"
        - name: PORT
          value: "3000"
        - name: WHATSAPP_BRIDGE_URL
          value: "http://localhost:8080"
        - name: GCS_SESSION_BUCKET
          value: "PROJECT_ID-whatsapp-sessions"
        - name: GCS_SESSION_OBJECT_NAME
          value: "whatsapp.db"
        - name: OAUTH_ENABLED
          value: "true"
        - name: LOG_LEVEL
          value: "INFO"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: whatsapp-mcp-google-client-id
              key: latest
        - name: OAUTH_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: whatsapp-mcp-oauth-audience
              key: latest
        # Optional: Supabase secrets (uncomment if using Supabase)
        # - name: SUPABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: whatsapp-mcp-supabase-url
        #       key: latest
        # - name: SUPABASE_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: whatsapp-mcp-supabase-key
        #       key: latest
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: whatsapp-mcp-database-url
        #       key: latest
        # Optional: Separate session database (uncomment to use Supabase for sessions)
        # - name: WHATSAPP_SESSION_DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: whatsapp-mcp-session-dsn
        #       key: latest
        resources:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 3000
            httpHeaders:
            - name: User-Agent
              value: "GoogleHC/1.0"
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 30
          failureThreshold: 3
      scaling:
        minScale: 0
        maxScale: 10
  traffic:
  - percent: 100
    latestRevision: true
